kind: pipeline
workspace:
  base: /drone/src
  path: go
pipeline:
  build:
    image: 'golang:1.13'
    commands:
      - 'go get -t ./...'
      - 'go build'
  public-dev:
    image: plugins/docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    commands:
      - 'docker login --username=潘金天1992 --password=xinyoulingxiyidiantong. registry.cn-beijing.aliyuncs.com'
      - 'docker build --rm  -t go-learn .'
      - 'docker tag go-learn registry.cn-beijing.aliyuncs.com/frode/go:master'
      - 'docker push registry.cn-beijing.aliyuncs.com/frode/go:master'
    when:
      branch: master
      event: push
  rancher-online:
    image: peloton/drone-rancher
    url: 'http://182.92.189.28:8080'
    access_key: 9DC5B73C654423356E28
    secret_key: 1ZR2QFbNq38zQK9aVNSEwQGsAXEHL2RrMueMt2GN
    service: go-learn/go-learn
    docker_image: registry-vpc.cn-beijing.aliyuncs.com/frode/go:master
    start_first: false
    confirm: true
    timeout: 180
    when:
      branch: master
      event: push